### ISSUE TITLE
Consider re-licensing under MIT License

### ISSUE THREAD

**Issue by jamesmunns** [heartsucker/iron-csrf#1]
The parent project (Iron) is licensed under the MIT License (see [here](https://github.com/iron/iron/blob/master/LICENSE)). Consider re-licensing your project under the same license.

I would guess it would be likely to cause confusion if sub-parts have a more restrictive license. My license-foo is also somewhat weak, however due to how the rust compiler works, this component will be statically linked, so IIRC any project using this library must use a GPL3 compatible license.

**Comment by heartsucker** [comment]
Done.
